global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using UniversalLauncherWinUI.Common;
global using UniversalLauncherWinUI.ViewModels;
global using UniversalLauncherWinUI.Views;
global using WinUICommunity;
global using static UniversalLauncherWinUI.Common.AppHelper;
global using static UniversalLauncherWinUI.Common.LoggerSetup;
